### ISSUE TITLE
Add propagation format config

### ISSUE THREAD

**Issue by jcchavezs** [hypertrace/agent-config#18]
Currently it is not possible to configure the propagation format and the responsibility is push to agents. We could do something like

```proto
message AgentConfig {
    ...
    // propagationFormats list the supported propagation formats
    repeated PropagationFormat propagationFormats = 4;
}
...

enum PropagationFormat {
    // B3 propagation format, agents should support both multi and single value formats
    // see https://github.com/openzipkin/b3-propagation
    B3 = 0;

    // W3C Propagation format
    // see https://www.w3.org/TR/trace-context/
    TRACE_CONTEXT = 1;
}
```

The idea of accepting an array is that users can support many propagation formats to ease the migration (if willing to) and to also reduce the friction of introducing the hypertrace agents.

Ping @hypertrace/agent-maintainers

**Comment by pavolloffay** [comment]
+1, how does the enum look like in yaml config?

**Comment by jcchavezs** [comment]
Good question. Let me see.

**Comment by jcchavezs** [comment]
So using the proto marshaler/unmarshaler you can basically use

```json
{"propagationFormats":["B3","TRACE_CONTEXT"]}
```
or 

```yaml
propagationFormats:
    - "B3"
    - "TRACE_CONTEXT"
```

**Comment by pavolloffay** [comment]
LGTM, I would also propose to change the `TRACE_CONTEXT` to `W3C_TRACE_CONTEXT` to avoid any ambiguity. This is how OTEL and Jeeger (just `w3c`) refers to it https://github.com/open-telemetry/opentelemetry-specification/blob/09f31a51bf2d9e3b563e52230a27013449475da8/specification/context/api-propagators.md#propagators-distribution

**Comment by jcchavezs** [comment]
Sounds good to me.
