### ISSUE TITLE
Include units in the time config fields

### ISSUE THREAD

**Issue by jcchavezs** [hypertrace/agent-config#27]
When it comes to units and more so when it comes to seconds, it is very ambiguous what kind of unit should be used for values. Specifically in https://github.com/hypertrace/agent-config/commit/5d884ee42b5c053ced0063c05039f7f1038b4cd8#diff-3eaf2c85e69e9ea4804954dd98f3b0e3de1047da36714aef929a41efac2fbd54R51 when working with the env vars or the config values it is hard to guess what unit it is unless we go to documentation. We should change it into something like `pollPeriodInSecs` to discard any ambiguity.

I also makes me wonder the reasoning for choosing seconds over millis (not saying I would change it, just curious about the reasoning) as 2.5 (float) sounds a legit value (but maybe not too different from 2 or 3).

Ping @hypertrace/agent-maintainers

**Comment by pavolloffay** [comment]
It's fine to add suffix with units.

For OPA poll period the seconds seems reasonable. I am not sure if somebody would like to query the OPA service every X millis. IIRC the default value in the old config was 30s.

**Comment by jcchavezs** [comment]
Fixed by https://github.com/hypertrace/agent-config/pull/29
