### ISSUE TITLE
Change field names from camel case to snake case

### ISSUE THREAD

**Issue by mohit-a21** [hypertrace/agent-config#40]
Protobuf style guide defines the name of fields should be `underscore_separated_names` (Snake case) [here](https://developers.google.com/protocol-buffers/docs/style#message_and_field_names). While integrating this config with the envoy, I am running into issues where default proto files generated keep the camel casing in field and methods but is converted to lower case when the validation files are generated using `https://github.com/envoyproxy/protoc-gen-validate`

**Comment by mohit-a21** [comment]
cc: @davexroth, @jcchavezs, @pavolloffay

**Comment by jcchavezs** [comment]
Will this break existing YAML files user configs?

**Comment by mohit-a21** [comment]
```
serviceName: oldC
reporting:
  endpoint: http://127.0.0.1:9411/api/v2/spans
```

```
service_name: newC
reporting:
  endpoint: http://127.0.0.1:9411/api/v2/spans
```
Both configs seem to be working with the goagent.
