### ISSUE TITLE
Propagation formats are not listed in ENV vars table

### ISSUE THREAD

**Issue by pavolloffay** [hypertrace/agent-config#43]
https://github.com/hypertrace/agent-config/blob/main/ENV_VARS.md 

https://github.com/hypertrace/agent-config/blob/main/config.proto#L55

**Comment by mohit-a21** [comment]
@jcchavezs  Do we have support for defining env vars for repeated fields?

**Comment by jcchavezs** [comment]
Yeah before I went on sickleave this was WIP
