### ISSUE TITLE
Disable enable agent through config

### ISSUE THREAD

**Issue by mohit-a21** [hypertrace/agent-config#45]
We should be able to enable/disable agents through the config. We can define `enabled` flag in `AgentConfig`.

```
message AgentConfig {
 google.protobuf.BoolValue enabled = 5;
}
```
If enabled is set to false, then the agent will not do tracing and data capture.

**Comment by pavolloffay** [comment]
+1 LGTM

**Comment by jcchavezs** [comment]
+1
