### ISSUE TITLE
Add CI badge

### ISSUE THREAD

**Issue by pavolloffay** [hypertrace/agent-config#7]

**Comment by jcchavezs** [comment]
While I usually like this kind of thing I am curious about the purpose here
since we are not building or testing anything here.

**Comment by pavolloffay** [comment]
the ci is linting the protos, users should know that it exists. By seeing a CI badge consumers know that source is being tested in some way.

**Comment by jcchavezs** [comment]
i think this is failing as currently it is red because of my previous PR failed so probably we need the badge only pointing to `main`? https://github.com/hypertrace/agent-config/actions/runs/359845426
